routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which    
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Auth::routes(['register' => false]);
Route::get('clear', function () {
    \Artisan::call('config:cache');
    \Artisan::call('cache:clear');
    \Artisan::call('route:clear');
    \Artisan::call('view:clear');
    \Artisan::call('storage:link');
    echo "ok";
});
Route::get('/register', function () {
    return redirect('login');
});
Route::get('/', [App\Http\Controllers\WebsiteController::class, 'index'])->name('frontpage');
Route::get('/index', [App\Http\Controllers\WebsiteController::class, 'index'])->name('index');

Route::get('/privacy-policy', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('privacy.policy');
Route::get('/terms-of-service', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('terms.of.service');
Route::get('/cookies-policy', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('cookies.policy');
Route::get('/returns-policy', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('returns.policy');
Route::get('/shipping-terms', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('shipping.terms');

Route::get('/en/user/manual', [App\Http\Controllers\WebsiteController::class, 'userManualEn'])->name('user.manualEn');
Route::get('/en/user/manual/introduction', [App\Http\Controllers\WebsiteController::class, 'introduction'])->name('introduction');
Route::get('/en/user/manual/generaldescription', [App\Http\Controllers\WebsiteController::class, 'generaldescription'])->name('generaldescription');
Route::get('/en/user/manual/intendeduse', [App\Http\Controllers\WebsiteController::class, 'intendeduse'])->name('intendeduse');
Route::get('/en/user/manual/colorlighttherapy', [App\Http\Controllers\WebsiteController::class, 'colorlighttherapy'])->name('colorlighttherapy');
Route::get('/en/user/manual/safetyimportant', [App\Http\Controllers\WebsiteController::class, 'safetyimportant'])->name('safetyimportant');
Route::get('/en/user/manual/electromagnetic', [App\Http\Controllers\WebsiteController::class, 'electromagnetic'])->name('electromagnetic');
Route::get('/en/user/manual/setupdevice', [App\Http\Controllers\WebsiteController::class, 'setupdevice'])->name('setupdevice');
Route::get('/en/user/manual/appledevices', [App\Http\Controllers\WebsiteController::class, 'appledevices'])->name('appledevices');
Route::get('/en/user/manual/readingmode', [App\Http\Controllers\WebsiteController::class, 'readingmode'])->name('readingmode');
Route::get('/en/user/manual/wakeuphelp', [App\Http\Controllers\WebsiteController::class, 'wakeuphelp'])->name('wakeuphelp');
Route::get('/en/user/manual/sleepaid', [App\Http\Controllers\WebsiteController::class, 'sleepaid'])->name('sleepaid');
Route::get('/en/user/manual/lightcontrol', [App\Http\Controllers\WebsiteController::class, 'lightcontrol'])->name('lightcontrol');
Route::get('/en/user/manual/musicmeditations', [App\Http\Controllers\WebsiteController::class, 'musicmeditations'])->name('musicmeditations');
Route::get('/en/user/manual/lightcolortherapy', [App\Http\Controllers\WebsiteController::class, 'lightcolortherapy'])->name('lightcolortherapy');
Route::get('/en/user/manual/personalsleephealthcoach', [App\Http\Controllers\WebsiteController::class, 'personalsleephealthcoach'])->name('personalsleephealthcoach');
Route::get('/en/user/manual/offlineuse', [App\Http\Controllers\WebsiteController::class, 'offlineuse'])->name('offlineuse');
Route::get('/en/user/manual/troubleshooting', [App\Http\Controllers\WebsiteController::class, 'troubleshooting'])->name('troubleshooting');
Route::get('/en/user/manual/storagecare', [App\Http\Controllers\WebsiteController::class, 'storagecare'])->name('storagecare');
Route::get('/en/user/manual/recycling', [App\Http\Controllers\WebsiteController::class, 'recycling'])->name('recycling');
Route::get('/en/user/manual/warrantyandsupport', [App\Http\Controllers\WebsiteController::class, 'warrantyandsupport'])->name('warrantyandsupport');
Route::get('/en/user/manual/technicaldata', [App\Http\Controllers\WebsiteController::class, 'technicaldata'])->name('technicaldata');

Route::get('/en/user/manual/updatefirmware', [App\Http\Controllers\WebsiteController::class, 'updatefirmware'])->name('updatefirmware');


Route::get('/de/user/manual', [App\Http\Controllers\WebsiteController::class, 'userManualDe'])->name('user.manualDe');
Route::get('/de/user/manual/introduction', [App\Http\Controllers\WebsiteController::class, 'deIntroduction'])->name('de.introduction');
Route::get('/de/user/manual/generaldescription', [App\Http\Controllers\WebsiteController::class, 'deGeneraldescription'])->name('de.generaldescription');
Route::get('/de/user/manual/intendeduse', [App\Http\Controllers\WebsiteController::class, 'deIntendeduse'])->name('de.intendeduse');
Route::get('/de/user/manual/colorlighttherapy', [App\Http\Controllers\WebsiteController::class, 'deColorlighttherapy'])->name('de.colorlighttherapy');
Route::get('/de/user/manual/safetyimportant', [App\Http\Controllers\WebsiteController::class, 'deSafetyimportant'])->name('de.safetyimportant');
Route::get('/de/user/manual/electromagnetic', [App\Http\Controllers\WebsiteController::class, 'deElectromagnetic'])->name('de.electromagnetic');
Route::get('/de/user/manual/setupdevice', [App\Http\Controllers\WebsiteController::class, 'deSetupdevice'])->name('de.setupdevice');
Route::get('/de/user/manual/appledevices', [App\Http\Controllers\WebsiteController::class, 'deAppledevices'])->name('de.appledevices');
Route::get('/de/user/manual/readingmode', [App\Http\Controllers\WebsiteController::class, 'deReadingmode'])->name('de.readingmode');
Route::get('/de/user/manual/wakeuphelp', [App\Http\Controllers\WebsiteController::class, 'deWakeuphelp'])->name('de.wakeuphelp');
Route::get('/de/user/manual/sleepaid', [App\Http\Controllers\WebsiteController::class, 'deSleepaid'])->name('de.sleepaid');
Route::get('/de/user/manual/lightcontrol', [App\Http\Controllers\WebsiteController::class, 'deLightcontrol'])->name('de.lightcontrol');
Route::get('/de/user/manual/musicmeditations', [App\Http\Controllers\WebsiteController::class, 'deMusicmeditations'])->name('de.musicmeditations');
Route::get('/de/user/manual/lightcolortherapy', [App\Http\Controllers\WebsiteController::class, 'deLightcolortherapy'])->name('de.lightcolortherapy');
Route::get('/de/user/manual/personalsleephealthcoach', [App\Http\Controllers\WebsiteController::class, 'dePersonalsleephealthcoach'])->name('de.personalsleephealthcoach');
Route::get('/de/user/manual/offlineuse', [App\Http\Controllers\WebsiteController::class, 'deOfflineuse'])->name('de.offlineuse');
Route::get('/de/user/manual/troubleshooting', [App\Http\Controllers\WebsiteController::class, 'deTroubleshooting'])->name('de.troubleshooting');
Route::get('/de/user/manual/storagecare', [App\Http\Controllers\WebsiteController::class, 'deStoragecare'])->name('de.storagecare');
Route::get('/de/user/manual/recycling', [App\Http\Controllers\WebsiteController::class, 'deRecycling'])->name('de.recycling');
Route::get('/de/user/manual/warrantyandsupport', [App\Http\Controllers\WebsiteController::class, 'deWarrantyandsupport'])->name('de.warrantyandsupport');
Route::get('/de/user/manual/technicaldata', [App\Http\Controllers\WebsiteController::class, 'deTechnicaldata'])->name('de.technicaldata');

Route::get('/de/user/manual/updatefirmware', [App\Http\Controllers\WebsiteController::class, 'deUpdatefirmware'])->name('de.updatefirmware');








Route::get('/home', function () {
    return redirect('keyword');
});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/languages',  App\Http\Controllers\LanguagesController::class);
    Route::resource('/keyword', App\Http\Controllers\KeywordController::class);
    Route::resource('/content', App\Http\Controllers\ContentController::class);
    Route::post('ckeditor/image_upload', [App\Http\Controllers\WebsiteController::class, 'upload'])->name('upload');
    
    // Route::post('logout', 'Auth\LoginController@logout');
});
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/partials/actions.blade.php
<div class="button items">
@php
    $routeName = Route::currentRouteName();
    $route = str_replace(".index","",$routeName);

    $all_routes =array("user","music","transactionhistory");

    $delete_routes = array("keyword","faq","ticketcategory","musictype","artist","category","alarmdurationtime","alarmtype","supportticket","music","therapy","frequencytype");
    
    $edit_routes = array("languages","keyword","faq","ticketcategory","musictype","artist","category","alarmdurationtime","alarmtype","supportticket","content","mobileversion","music","user","therapy","frequencytype");

    $id = encrypt($id);
@endphp

@if(in_array($route, $all_routes))
    <!--<a href="{{ route($route.'.show', $id) }}" title="Show" class="btn btn-sm btn-success">
        <i class="fa fa-eye"></i>
    </a>-->
    <a href="{{ route($route.'.show', $id) }}" class="btn btn-sm btn-icon view rounded-circle" title="View">
        <i class="bx bx-show-alt"></i>
    </a>
@endif

@if(in_array($route, $edit_routes))
    <!--<a href="{{ route($route.'.edit', $id) }}" title="Edit" class="btn btn-sm btn-primary">
        <i class="fa fa-edit"></i>
    </a>-->
    <a href="{{ route($route.'.edit', $id) }}" class="btn btn-sm btn-icon edit rounded-circle" title="Edit">
        <i class="bx bx-edit-alt"></i>
    </a>
@endif

@if(in_array($route, $delete_routes))
    <!--<a href="javascript:{}" title="Delete" class="action-delete btn btn-sm btn-danger" entry-id="{{ $id }}" > 
        <i class="fa fa-trash-alt"></i>
    </a>-->
    
    <a href="javascript:void(0);" class="action-delete btn btn-sm btn-icon delete rounded-circle" title="Delete" entry-id="{{ $id }}">
        <i class="bx bx-trash"></i>
    </a>
@endif
</div>

resources/views/partials/alert.blade.php
 <!-- end page title -->
 @if(session('success'))
     <div class="row mb-2">
         <div class="col-lg-12">
             <div class="alert alert-success" role="alert">
                 <button type="button" class="close" data-dismiss="alert" aria-label="X">
                     <span aria-hidden="true">&times;</span>
                 </button>
                 {{ session('success') }}
             </div>
         </div>
     </div>
@endif
@if(session('danger'))
     <div class="row mb-2">
         <div class="col-lg-12">
             <div class="alert alert-danger" role="alert">
                 {{ session('danger') }}
             </div>
         </div>
     </div>
@endif
@if ($errors->any())
    <div class="row mb-2">
         <div class="col-lg-12">
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    {{ $error }}
                @endforeach
            </div>
        </div>
    </div>
@endif

resources/views/partials/sidebar.blade.php
    <aside class="vertical-menu">

        <div data-simplebar class="h-100">

            <!--- Sidemenu -->
            <div id="sidebar-menu">
                <!-- Left Menu Start -->
                <!-- Admin show menu start -->


                <ul class="metismenu list-unstyled" id="side-menu">
                    <li class="menu-title">{{ trans('cruds.menu') }}</li>
                    <li class="{{ request()->is('languages') || request()->is('languages/*') ? 'mm-active' : '' }}">
                        <a href="{{ route('languages.index') }}" class="waves-effect {{ request()->is('languages') || request()->is('languages/*') ? 'active' : '' }}">
                            <span>{{ trans('cruds.languages.title') }}</span>
                        </a>
                    </li>
                    <li class="{{ request()->is('keyword') || request()->is('keyword/*') ? 'mm-active' : '' }}">
                        <a href="{{ route('keyword.index') }}" class="waves-effect {{ request()->is('keyword') || request()->is('keyword/*') ? 'active' : '' }}">
                            <span>{{ trans('cruds.keyword.title') }}</span>
                        </a>
                    </li>
                    <li class="{{ request()->is('content') || request()->is('content/*') ? 'mm-active' : '' }}">
                        <a href="{{ route('content.index') }}" class="waves-effect {{ request()->is('content') || request()->is('content/*') ? 'active' : '' }}">
                            <span>{{ trans('cruds.content.title') }}</span>
                        </a>
                    </li>
                </ul>
                <!-- Admin show menu end -->
            </div>
            <!-- Sidebar -->
        </div>
    </aside>
    <!-- Left Sidebar End -->

resources/views/partials/switch.blade.php
@php $id = encrypt($id); @endphp 
<div class="custom-control custom-switch">
    <input type="checkbox" class="custom-control-input switch_checkbox_btn" id="customSwitch{{ $id }}"
         entry-id="{{ $id }}" {{ ($is_active) ? 'checked': '' }}>
    <label class="custom-control-label" for="customSwitch{{ $id }}"></label>
</div>

resources/views/partials/topbar.blade.php
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box ">
                <a href="" class="logo logo-dark text-dark h3">
                    <span class="logo-sm">
                        Samina
                    </span>
                    <span class="logo-lg">
                        Samina
                        <!-- <img src="{{ asset('img/logo.png')}}" class="img-fluid" alt="Logo"  alt="" height="17"> -->
                    </span>
                </a>

                <a href="" class="logo logo-light text-white h3">
                    <span class="logo-sm">
                        <img src="{{ asset('public/assets/backend/images/logo.png')}}" class="img-fluid mt-5" alt="Logo"  alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{{ asset('public/assets/backend/images/logo.png')}}" class="img-fluid mt-5" alt="Logo"  alt=""
                            height="auto">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect mt-4" id="vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>
        </div>

        <div class="d-flex">
            <div class="dropdown ">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user"
                        src="{{ asset('public/assets/backend/images/users/avatar-1.jpg')}}"
                        alt="Header Avatar">
                    <span class="d-none d-xl-inline-block ml-1">Admin</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <!-- item-->
                   <!--  <a class="dropdown-item" href="#"><i class="bx bx-user font-size-16 align-middle mr-1"></i>
                        Profile</a> -->
                    <a class="dropdown-item text-danger nav-link" href="#"
                        onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                        <i class="bx bx-power-off font-size-16 align-middle mr-1 text-danger"></i>
                        Logout
                    </a>
                    <form id="logoutform" action="{{ route('logout') }}" method="POST"
                        style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </div>
            </div>

            <div class="dropdown d-none">
                <button type="button" class="btn header-item noti-icon right-bar-toggle waves-effect">
                    <i class="bx bx-cog bx-spin"></i>
                </button>
            </div>

        </div>
    </div>
</header> <!-- ========== Left Sidebar Start ========== -->