routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which    
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Auth::routes(['register' => false]);
Route::get('clear', function () {
    \Artisan::call('config:cache');
    \Artisan::call('cache:clear');
    \Artisan::call('route:clear');
    \Artisan::call('view:clear');
    \Artisan::call('storage:link');
    echo "ok";
});
Route::get('/register', function () {
    return redirect('login');
});
Route::get('/', [App\Http\Controllers\WebsiteController::class, 'index'])->name('frontpage');
Route::get('/index', [App\Http\Controllers\WebsiteController::class, 'index'])->name('index');

Route::get('/privacy-policy', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('privacy.policy');
Route::get('/terms-of-service', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('terms.of.service');
Route::get('/cookies-policy', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('cookies.policy');
Route::get('/returns-policy', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('returns.policy');
Route::get('/shipping-terms', [App\Http\Controllers\WebsiteController::class, 'contentPage'])->name('shipping.terms');

Route::get('/en/user/manual', [App\Http\Controllers\WebsiteController::class, 'userManualEn'])->name('user.manualEn');
Route::get('/en/user/manual/introduction', [App\Http\Controllers\WebsiteController::class, 'introduction'])->name('introduction');
Route::get('/en/user/manual/generaldescription', [App\Http\Controllers\WebsiteController::class, 'generaldescription'])->name('generaldescription');
Route::get('/en/user/manual/intendeduse', [App\Http\Controllers\WebsiteController::class, 'intendeduse'])->name('intendeduse');
Route::get('/en/user/manual/colorlighttherapy', [App\Http\Controllers\WebsiteController::class, 'colorlighttherapy'])->name('colorlighttherapy');
Route::get('/en/user/manual/safetyimportant', [App\Http\Controllers\WebsiteController::class, 'safetyimportant'])->name('safetyimportant');
Route::get('/en/user/manual/electromagnetic', [App\Http\Controllers\WebsiteController::class, 'electromagnetic'])->name('electromagnetic');
Route::get('/en/user/manual/setupdevice', [App\Http\Controllers\WebsiteController::class, 'setupdevice'])->name('setupdevice');
Route::get('/en/user/manual/appledevices', [App\Http\Controllers\WebsiteController::class, 'appledevices'])->name('appledevices');
Route::get('/en/user/manual/readingmode', [App\Http\Controllers\WebsiteController::class, 'readingmode'])->name('readingmode');
Route::get('/en/user/manual/wakeuphelp', [App\Http\Controllers\WebsiteController::class, 'wakeuphelp'])->name('wakeuphelp');
Route::get('/en/user/manual/sleepaid', [App\Http\Controllers\WebsiteController::class, 'sleepaid'])->name('sleepaid');
Route::get('/en/user/manual/lightcontrol', [App\Http\Controllers\WebsiteController::class, 'lightcontrol'])->name('lightcontrol');
Route::get('/en/user/manual/musicmeditations', [App\Http\Controllers\WebsiteController::class, 'musicmeditations'])->name('musicmeditations');
Route::get('/en/user/manual/lightcolortherapy', [App\Http\Controllers\WebsiteController::class, 'lightcolortherapy'])->name('lightcolortherapy');
Route::get('/en/user/manual/personalsleephealthcoach', [App\Http\Controllers\WebsiteController::class, 'personalsleephealthcoach'])->name('personalsleephealthcoach');
Route::get('/en/user/manual/offlineuse', [App\Http\Controllers\WebsiteController::class, 'offlineuse'])->name('offlineuse');
Route::get('/en/user/manual/troubleshooting', [App\Http\Controllers\WebsiteController::class, 'troubleshooting'])->name('troubleshooting');
Route::get('/en/user/manual/storagecare', [App\Http\Controllers\WebsiteController::class, 'storagecare'])->name('storagecare');
Route::get('/en/user/manual/recycling', [App\Http\Controllers\WebsiteController::class, 'recycling'])->name('recycling');
Route::get('/en/user/manual/warrantyandsupport', [App\Http\Controllers\WebsiteController::class, 'warrantyandsupport'])->name('warrantyandsupport');
Route::get('/en/user/manual/technicaldata', [App\Http\Controllers\WebsiteController::class, 'technicaldata'])->name('technicaldata');

Route::get('/en/user/manual/updatefirmware', [App\Http\Controllers\WebsiteController::class, 'updatefirmware'])->name('updatefirmware');


Route::get('/de/user/manual', [App\Http\Controllers\WebsiteController::class, 'userManualDe'])->name('user.manualDe');
Route::get('/de/user/manual/introduction', [App\Http\Controllers\WebsiteController::class, 'deIntroduction'])->name('de.introduction');
Route::get('/de/user/manual/generaldescription', [App\Http\Controllers\WebsiteController::class, 'deGeneraldescription'])->name('de.generaldescription');
Route::get('/de/user/manual/intendeduse', [App\Http\Controllers\WebsiteController::class, 'deIntendeduse'])->name('de.intendeduse');
Route::get('/de/user/manual/colorlighttherapy', [App\Http\Controllers\WebsiteController::class, 'deColorlighttherapy'])->name('de.colorlighttherapy');
Route::get('/de/user/manual/safetyimportant', [App\Http\Controllers\WebsiteController::class, 'deSafetyimportant'])->name('de.safetyimportant');
Route::get('/de/user/manual/electromagnetic', [App\Http\Controllers\WebsiteController::class, 'deElectromagnetic'])->name('de.electromagnetic');
Route::get('/de/user/manual/setupdevice', [App\Http\Controllers\WebsiteController::class, 'deSetupdevice'])->name('de.setupdevice');
Route::get('/de/user/manual/appledevices', [App\Http\Controllers\WebsiteController::class, 'deAppledevices'])->name('de.appledevices');
Route::get('/de/user/manual/readingmode', [App\Http\Controllers\WebsiteController::class, 'deReadingmode'])->name('de.readingmode');
Route::get('/de/user/manual/wakeuphelp', [App\Http\Controllers\WebsiteController::class, 'deWakeuphelp'])->name('de.wakeuphelp');
Route::get('/de/user/manual/sleepaid', [App\Http\Controllers\WebsiteController::class, 'deSleepaid'])->name('de.sleepaid');
Route::get('/de/user/manual/lightcontrol', [App\Http\Controllers\WebsiteController::class, 'deLightcontrol'])->name('de.lightcontrol');
Route::get('/de/user/manual/musicmeditations', [App\Http\Controllers\WebsiteController::class, 'deMusicmeditations'])->name('de.musicmeditations');
Route::get('/de/user/manual/lightcolortherapy', [App\Http\Controllers\WebsiteController::class, 'deLightcolortherapy'])->name('de.lightcolortherapy');
Route::get('/de/user/manual/personalsleephealthcoach', [App\Http\Controllers\WebsiteController::class, 'dePersonalsleephealthcoach'])->name('de.personalsleephealthcoach');
Route::get('/de/user/manual/offlineuse', [App\Http\Controllers\WebsiteController::class, 'deOfflineuse'])->name('de.offlineuse');
Route::get('/de/user/manual/troubleshooting', [App\Http\Controllers\WebsiteController::class, 'deTroubleshooting'])->name('de.troubleshooting');
Route::get('/de/user/manual/storagecare', [App\Http\Controllers\WebsiteController::class, 'deStoragecare'])->name('de.storagecare');
Route::get('/de/user/manual/recycling', [App\Http\Controllers\WebsiteController::class, 'deRecycling'])->name('de.recycling');
Route::get('/de/user/manual/warrantyandsupport', [App\Http\Controllers\WebsiteController::class, 'deWarrantyandsupport'])->name('de.warrantyandsupport');
Route::get('/de/user/manual/technicaldata', [App\Http\Controllers\WebsiteController::class, 'deTechnicaldata'])->name('de.technicaldata');

Route::get('/de/user/manual/updatefirmware', [App\Http\Controllers\WebsiteController::class, 'deUpdatefirmware'])->name('de.updatefirmware');








Route::get('/home', function () {
    return redirect('keyword');
});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/languages',  App\Http\Controllers\LanguagesController::class);
    Route::resource('/keyword', App\Http\Controllers\KeywordController::class);
    Route::resource('/content', App\Http\Controllers\ContentController::class);
    Route::post('ckeditor/image_upload', [App\Http\Controllers\WebsiteController::class, 'upload'])->name('upload');
    
    // Route::post('logout', 'Auth\LoginController@logout');
});
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Content.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Content extends Model
{
    use HasFactory;
    protected $table = 'contents';
}

app/Http/Controllers/ContentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Storage;

use App\Models\Content;
use App\Models\Languages;
use App\Helpers\Helper;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contents = Content::groupBy('code')->get();
        $languages  = Languages::orderBy('id', 'asc')->get();
        return view('backend.content.index', compact('contents', 'languages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $languages  = Languages::orderBy('id', 'asc')->get();
        return view('backend.content.create', compact('languages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $checkKeyword = Content::where('code', $request->keyword)->first();
        if ($checkKeyword) {
            return redirect()->back()->with("danger", "keyword already used");
        }
        $languages = Languages::all();
        foreach ($languages as $language) {
            $lang = $request['language_' . $language->code];
            if ($lang) {
                $keywordLanguage = new Content;
                $keywordLanguage->keyword_language = $lang;
                $keywordLanguage->code = str_replace(' ','_',strtolower($request->keyword));
                $keywordLanguage->language_id = $language->id;
                $keywordLanguage->save();
            }
        }
        $message = trans('message.create', ['entity' => trans('cruds.content.title_singular')]);
        return redirect()->route('content.index')->with('success', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Languages  $Languages
     * @return \Illuminate\Http\Response
     */
    public function show(Languages $Languages)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Languages  $Languages
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $id = Crypt::decrypt($id);
        $languages = Languages::orderBy('id', 'asc')->get();
        $keyword = Content::where('id',$id)->first();
        return view('backend.content.edit', compact('languages','keyword'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Content  $content
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Content $content)
    {
        $languages = Languages::all();
        foreach ($languages as $language) {
            $lang = $request['language_' . $language->code];
            if ($lang) {
                $keywordLanguage = Content::where(['code' => $content->code,'language_id' => $language->id])->first();
                if(!$keywordLanguage){
                    $keywordLanguage = new Content;
                }
                $keywordLanguage->keyword_language = $lang;
                $keywordLanguage->code = $content->code;
                $keywordLanguage->language_id = $language->id;
                $keywordLanguage->save();
            }
        }
        $message = trans('message.update', ['entity' => trans('cruds.content.title_singular')]);
        return redirect()->route('content.index')->with('success', $message);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\CarBrand  $carBrand
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        // try {
        //     if ($request->ajax()) {
        //         $id = Crypt::decrypt($request->id);
        //         Languages::where('id', $id)->delete();
        //         return response()->json(['success' => 1]);
        //     }
        // } catch (\Exception $e) {
        //     if ($request->ajax()) {
        //         return response()->json(['error' => 1, 'message' => $e->getMessage()]);
        //     }
        // }
    }
}

resources/views/backend/content/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="page-title-box d-flex align-items-center justify-content-between">
                    <h4>{{ trans('global.create') }} {{ trans('cruds.content.title_singular') }}</h4>
                </div>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('keyword.index') }}" class="btn btn-primary">Back</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        @include("partials.alert")
                        <form action="{{ route('content.store') }}" method="POST" enctype="multipart/form-data" id="add_form">
                            @csrf
                            <div class="form-group">
                                <label for="title">{{ trans('cruds.content.fields.keyword') }}<span class="required_class">*</span></label>
                                <input type="text" class="form-control" name="keyword" value="{{ old('keyword', isset($keyword->keyword) ? $keyword->keyword : '') }}" required="" />
                            </div>
                            @foreach($languages as $language)
                            <div class="form-group">
                                <label for="title">{{ ucfirst($language->name) }}<span class="required_class">*</span></label>
                                <textarea class="ckeditor  form-control" name="language_{{ $language->code }}"  required="" >{!! old('language_'.$language->code) !!}</textarea>
                            </div>
                            @endforeach
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>  
    </div>
</div>    
@endsection
@section('scripts')
<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.ckeditor').ckeditor();
    });
</script>
@endsection

resources/views/backend/content/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="page-title-box d-flex align-items-center justify-content-between">
                    <h4>{{ trans('global.update') }} {{ trans('cruds.content.title_singular') }}</h4>
                </div>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                    <a href="{{ route('keyword.index') }}" class="btn btn-primary">Back</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        @include("partials.alert")
                        <form action="{{ route("content.update", [$keyword->id]) }}" method="POST" enctype="multipart/form-data" id="add_form">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="title">{{ trans('cruds.content.fields.keyword') }}<span class="required_class">*</span></label>
                                <input type="text" class="form-control" name="keyword" value="{{ old('keyword', isset($keyword->code) ? $keyword->code : '') }}" required="" readonly=""/>
                            </div>
                            @foreach($languages as $key1 => $language)
                            <div class="form-group">
                                <label for="title">{{ ucfirst($language->name) }}<span class="required_class">*</span></label>
                                <?php $lanauge_content = \App\Helpers\Helper::getContent($keyword->code,$language->id); ?>
                                <textarea style="height:500px" class="ckeditor  form-control" name="language_{{ $language->code }}"  required="" >{!! $lanauge_content !!}</textarea>
                            </div>
                            @endforeach
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div> bv
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
    $(document).ready(function () {
        
        // CKEDITOR.replace('language_en', {
		// 	filebrowserUploadUrl: "{{route('upload', ['_token' => csrf_token() ])}}",
		// 	filebrowserUploadMethod: 'form'
		// });
        // CKEDITOR.replace('language_', {
		// 	filebrowserUploadUrl: "{{route('upload', ['_token' => csrf_token() ])}}",
		// 	filebrowserUploadMethod: 'form'
		// });
    });
</script>
@endsection

resources/views/backend/content/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h4>{{ trans('cruds.content.title_singular') }} {{ trans('global.list') }}</h4>
            </div>

            <div class="col-md-6">
                <div class="float-right">
                    <!-- <a href="{{ route('content.create') }}" class="btn btn-primary">
                        <i class="fa fa-plus"></i>
                        {{ trans('global.add') }} {{ trans('cruds.content.title_singular') }}
                    </a> -->
                </div>
            </div>
           
            <div class="col-md-12 mt-3">
               <div class="card">
                    <div class="card-body">
                        @include("partials.alert")
                        <div class="table-responsive">
                            <table class="data-table table table-bordered table-striped table-hover datatable datatable-User">
                                <thead>
                                    <tr>
                                        <th>{{ trans('cruds.content.fields.id') }}</th>
                                        <th>{{ trans('cruds.content.fields.keyword') }}</th>
                                        @foreach($languages as $language)
                                        <th>
                                            {{ ucfirst($language->name) }} 
                                        </th>      
                                        @endforeach
                                        <th>{{ trans('global.actions') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($contents as $key => $value)
                                    <tr data-entry-id="{{ $value->id }}">
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $value->code ?? ''}}</td>
                                        @foreach($languages as $key1 => $language)
                                        <td>
                                            <?php $lanauge_content = \App\Helpers\Helper::getContent($value->code,$language->id); ?>
                                            {!!  $lanauge_content !!}
                                        </td>      
                                        @endforeach
                                        <td>@include('partials.actions', ['id' => $value->id])</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection